### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Boryyy** [999Samurai/InstagramReport#1]
![image](https://user-images.githubusercontent.com/60760570/95026366-2c687580-0691-11eb-8f2a-33aaec7e2756.png)
how to fix this ? 
thanks

**Comment by 999Samurai** [comment]
Install Firefox browser, or if you have it try to open it and do the first steps and try.

**Comment by Boryyy** [comment]
thanks for your time , i fixed that , what about this ?
![image](https://user-images.githubusercontent.com/60760570/95026646-1fe51c80-0693-11eb-810d-0fad2ef1e195.png)
sorry but i really need this one

**Comment by 999Samurai** [comment]
It is integrated in a discord bot, did you put a token or a working token?

**Comment by Boryyy** [comment]
where should i put the token?

**Comment by Boryyy** [comment]
can i add you in discord?

**Comment by 999Samurai** [comment]
You should insert the token in bot.run('token'), in the last line

**Comment by Boryyy** [comment]
![image](https://user-images.githubusercontent.com/60760570/95027057-f7125680-0695-11eb-8146-018988c432bb.png)
still

**Comment by 999Samurai** [comment]
Pretty sure the discord token is wrong, did you create an app in https://discord.com/developers/applications?

**Comment by Boryyy** [comment]
![image](https://user-images.githubusercontent.com/60760570/95027230-3c835380-0697-11eb-94d7-02034a7d61a9.png)

ok my bad , thanks for your time btw  <3

**Comment by 999Samurai** [comment]
Read the readme of the repository to setup the accounts

**Comment by Boryyy** [comment]
where do i put the account ?
![image](https://user-images.githubusercontent.com/60760570/95027359-38a40100-0698-11eb-89f8-5187eccfadfd.png)

its stuck like this

**Comment by Boryyy** [comment]
the account it should report i mean*

**Comment by 999Samurai** [comment]
You should invite the bot to your server and use the prefix insta!, so the command will be insta!ban <username> <number of the account to use>

**Comment by Boryyy** [comment]
how do i do that? can you send me a video or somthing

**Comment by 999Samurai** [comment]
https://discordapp.com/oauth2/authorize?client_id=BOTIDHERE&scope=bot&permissions=0

You should change the "botidhere" with your bot id and invite it to your server.

**Comment by Boryyy** [comment]
![image](https://user-images.githubusercontent.com/60760570/95027619-48244980-069a-11eb-89fe-3f00a4ed1af8.png)

i did this 

still nothing
 
![image](https://user-images.githubusercontent.com/60760570/95027634-6427eb00-069a-11eb-8442-916539d26a03.png)

**Comment by 999Samurai** [comment]
Now in the channel you do insta!ban username_to_ban number_of_the_account_to_use

**Comment by Boryyy** [comment]
ok thanks for your time , sorry for wasting it , <3 <3 best of luck

**Comment by 999Samurai** [comment]
No problem, closing the issue.

**Comment by Boryyy** [comment]
the bot is doing nothing now , goes to the report account , goes to my profile , and back ? why ?
