### ISSUE TITLE
why it shows this after the reports?

### ISSUE THREAD

**Issue by Boryyy** [999Samurai/InstagramReport#2]
![image](https://user-images.githubusercontent.com/60760570/95028202-e0bcc880-069e-11eb-9f06-770569bcfc1b.png)

**Comment by 999Samurai** [comment]
Do you have 5 accounts on the bot?

**Comment by Boryyy** [comment]
yes ?
even if i recode and add only 1 it still shows that

**Comment by 999Samurai** [comment]
at line 51, add a await before the "ctx.send"

**Comment by Boryyy** [comment]
if i do insta!ban random 1 it does the first browser , how i can do all 5? 1 2 3.. or ?

**Comment by 999Samurai** [comment]
You cant use all at the same time, the method i use isn't spam report. You need a account with 20k follows and you report it for impersonating

**Comment by Boryyy** [comment]
i get that , but why is this still showing with await 
![image](https://user-images.githubusercontent.com/60760570/95028860-df41cf00-06a3-11eb-85b7-83bd442aaaa2.png)

**Comment by 999Samurai** [comment]
If you can get me a gif of what is happening in the browser it will be easier for me

**Comment by Boryyy** [comment]
It finishes the report and it shows me that error , afrer it goes to explore , maybe that’s the point idk ? And sometimes it doesn’t pick the profile pic and just says tried 5 times try again

**Comment by 999Samurai** [comment]
I don't know what is happening to be honest. Sorry but i cant help

**Comment by Boryyy** [comment]
Ok last question, does the bot keep reporting the account or it stops at one time?

**Comment by 999Samurai** [comment]
It report one time and stop

**Comment by Boryyy** [comment]
Okay , so it doesn’t spam report non stop? And its like 100% if u have 10k-20k account or nobody knows?

**Comment by 999Samurai** [comment]
almost 100% to ban accounts with like max 5k

**Comment by Boryyy** [comment]
Okay thanks for everything, ur the best!
