### ISSUE TITLE
not working now

### ISSUE THREAD

**Issue by Boryyy** [999Samurai/InstagramReport#3]
![image](https://user-images.githubusercontent.com/60760570/95096156-35f2eb80-072c-11eb-99d5-d2d9914700ba.png)

insta!ban random 1 , wait 5 min doing nothing , not picking the profile pic , not reporting , why ?

**Comment by 999Samurai** [comment]
Do you have an folder named images in the same directory of the main.py?

**Comment by Boryyy** [comment]
![image](https://user-images.githubusercontent.com/60760570/95097451-cd0c7300-072d-11eb-85b4-b080b03da175.png)

yes?

**Comment by Boryyy** [comment]
i tried another account , still not saving the photo , not changing the name , idk why

**Comment by 999Samurai** [comment]
The account images are saving on the images folder?

**Comment by Boryyy** [comment]
yes , 1 of them only , the other ones nope

**Comment by 999Samurai** [comment]
Super weird, i can't help since i don't know what is happening

**Comment by Boryyy** [comment]
does the  "time.sleep(2)" help in some parts? maybe my internet is slow? or it doesn't matter

**Comment by 999Samurai** [comment]
Yes, it can be it too. Maybe you need to wait more time so put like 5 or 10 seconds instead of 2 or 5

**Comment by Boryyy** [comment]
can you tell me where to put them ? like it stuck at the part when saving the picture , and when saving settings after change the username

**Comment by 999Samurai** [comment]
Try using other username and tell me if the account image saves

**Comment by Boryyy** [comment]
yea it saves the image , but then it goes to my profile , stays like 1 second , goes back to the account_to_ban

**Comment by Boryyy** [comment]
maybe not finding xpath? or somthing

**Comment by 999Samurai** [comment]
May be, i will try to fix it, if i don't update the repository maybe i couldn't fix it
